name: Run checks

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Check format
        uses: jidicula/clang-format-action@v4.5.0
        with:
          clang-format-version: '14'
      - run: echo "🍏 This job's status is ${{ job.status }}."
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: lukka/get-cmake@latest
      - name: build
        run: |
          ls ${{ github.workspace }}
          mkdir build
          cd build
          cmake ../tests
          cmake --build .
      - name: run
        run: |
          cd build
          ./Google_Tests_run
