name: Run checks

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check format
        uses: jidicula/clang-format-action@v4.5.0
        with:
          clang-format-version: '14'
      - run: echo "🍏 This job's status is ${{ job.status }}."
